# Generated by Django 3.2.7 on 2021-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
